import { SearchResult } from "@/lib/finnhub";

export const TOP_50: SearchResult[] = [
  { symbol: "AAPL",  description: "Apple Inc.",                  type: "Common Stock" },
  { symbol: "MSFT",  description: "Microsoft Corporation",       type: "Common Stock" },
  { symbol: "NVDA",  description: "NVIDIA Corporation",          type: "Common Stock" },
  { symbol: "AMZN",  description: "Amazon.com Inc.",             type: "Common Stock" },
  { symbol: "GOOGL", description: "Alphabet Inc.",               type: "Common Stock" },
  { symbol: "META",  description: "Meta Platforms Inc.",         type: "Common Stock" },
  { symbol: "TSLA",  description: "Tesla Inc.",                  type: "Common Stock" },
  { symbol: "BRK.B", description: "Berkshire Hathaway Inc.",     type: "Common Stock" },
  { symbol: "JPM",   description: "JPMorgan Chase & Co.",        type: "Common Stock" },
  { symbol: "V",     description: "Visa Inc.",                   type: "Common Stock" },
  { symbol: "LLY",   description: "Eli Lilly and Company",       type: "Common Stock" },
  { symbol: "AVGO",  description: "Broadcom Inc.",               type: "Common Stock" },
  { symbol: "MA",    description: "Mastercard Inc.",             type: "Common Stock" },
  { symbol: "UNH",   description: "UnitedHealth Group Inc.",     type: "Common Stock" },
  { symbol: "XOM",   description: "Exxon Mobil Corporation",     type: "Common Stock" },
  { symbol: "JNJ",   description: "Johnson & Johnson",           type: "Common Stock" },
  { symbol: "HD",    description: "The Home Depot Inc.",         type: "Common Stock" },
  { symbol: "PG",    description: "Procter & Gamble Co.",        type: "Common Stock" },
  { symbol: "ABBV",  description: "AbbVie Inc.",                 type: "Common Stock" },
  { symbol: "MRK",   description: "Merck & Co. Inc.",            type: "Common Stock" },
  { symbol: "CVX",   description: "Chevron Corporation",         type: "Common Stock" },
  { symbol: "KO",    description: "The Coca-Cola Company",       type: "Common Stock" },
  { symbol: "PEP",   description: "PepsiCo Inc.",                type: "Common Stock" },
  { symbol: "BAC",   description: "Bank of America Corp.",       type: "Common Stock" },
  { symbol: "ADBE",  description: "Adobe Inc.",                  type: "Common Stock" },
  { symbol: "CRM",   description: "Salesforce Inc.",             type: "Common Stock" },
  { symbol: "MCD",   description: "McDonald's Corporation",      type: "Common Stock" },
  { symbol: "CSCO",  description: "Cisco Systems Inc.",          type: "Common Stock" },
  { symbol: "WMT",   description: "Walmart Inc.",                type: "Common Stock" },
  { symbol: "TXN",   description: "Texas Instruments Inc.",      type: "Common Stock" },
  { symbol: "NFLX",  description: "Netflix Inc.",                type: "Common Stock" },
  { symbol: "DIS",   description: "The Walt Disney Company",     type: "Common Stock" },
  { symbol: "TMO",   description: "Thermo Fisher Scientific",    type: "Common Stock" },
  { symbol: "ABT",   description: "Abbott Laboratories",         type: "Common Stock" },
  { symbol: "PM",    description: "Philip Morris International", type: "Common Stock" },
  { symbol: "GE",    description: "GE Aerospace",                type: "Common Stock" },
  { symbol: "NEE",   description: "NextEra Energy Inc.",         type: "Common Stock" },
  { symbol: "VZ",    description: "Verizon Communications",      type: "Common Stock" },
  { symbol: "COST",  description: "Costco Wholesale Corp.",      type: "Common Stock" },
  { symbol: "ACN",   description: "Accenture plc",               type: "Common Stock" },
  { symbol: "MDT",   description: "Medtronic plc",               type: "Common Stock" },
  { symbol: "HON",   description: "Honeywell International",     type: "Common Stock" },
  { symbol: "IBM",   description: "IBM Corporation",             type: "Common Stock" },
  { symbol: "UNP",   description: "Union Pacific Corporation",   type: "Common Stock" },
  { symbol: "RTX",   description: "RTX Corporation",             type: "Common Stock" },
  { symbol: "LOW",   description: "Lowe's Companies Inc.",       type: "Common Stock" },
  { symbol: "INTC",  description: "Intel Corporation",           type: "Common Stock" },
  { symbol: "AMGN",  description: "Amgen Inc.",                  type: "Common Stock" },
  { symbol: "SBUX",  description: "Starbucks Corporation",       type: "Common Stock" },
  { symbol: "AXP",   description: "American Express Company",    type: "Common Stock" },
];
